# Generated by Django 4.1.6 on 2023-09-29 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('time_to_read', models.IntegerField(default=5, verbose_name='ظول زمان خواندن مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, verbose_name='عنوان در url')),
                ('image', models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('first_paragraph', models.TextField(blank=True, null=True, verbose_name='اولبن متن مقاله')),
                ('second_paragraph', models.TextField(blank=True, null=True, verbose_name='دومین متن مقاله')),
                ('third_paragraph', models.TextField(blank=True, null=True, verbose_name='سومین متن مقاله')),
                ('forth_paragraph', models.TextField(blank=True, null=True, verbose_name='چهارمین متن مقاله')),
                ('fifth_paragraph', models.TextField(blank=True, null=True, verbose_name='پنجمین متن مقاله')),
                ('title_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='عنوان در جملات')),
                ('first_text_after_title', models.TextField(blank=True, null=True, verbose_name='اولین متن مقاله بعد عنوان')),
                ('second_text_after_title', models.TextField(blank=True, null=True, verbose_name='دومین متن مقاله بعد عنوان')),
                ('third_text_after_title', models.TextField(blank=True, null=True, verbose_name='سومین متن مقاله بعد عنوان')),
                ('first_question', models.CharField(blank=True, max_length=20, null=True, verbose_name='اولین سوال')),
                ('first_question_text', models.TextField(blank=True, null=True, verbose_name='اولین متن بعد سوال اول')),
                ('second_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='دومین عنوان')),
                ('second_title_text', models.TextField(blank=True, null=True, verbose_name='دومین متن بعد سوال دوم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال بودن')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریح ثبت')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نام دسته')),
                ('url_title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='نام در url')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'گروه دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='ArticleVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='ای پی کابر')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='مقاله')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربری که مشاهده کرده')),
            ],
            options={
                'verbose_name': 'مشاهده مقاله',
                'verbose_name_plural': 'لیست مشاهده مقاله',
            },
        ),
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/article-gallery', verbose_name='تصویر محصولات')),
                ('is_active', models.BooleanField(default=False, verbose_name='غیر/فعال')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articlecategory'),
        ),
    ]
