# Generated by Django 4.1.6 on 2023-09-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='first_question',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اولین سوال'),
        ),
        migrations.AlterField(
            model_name='article',
            name='second_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دومین عنوان'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان در جملات'),
        ),
    ]
