# Generated by Django 4.1.6 on 2023-09-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_first_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegallery',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='محصول'),
        ),
    ]
