# Generated by Django 4.1.6 on 2023-09-30 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articlegallery_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlegallery',
            name='is_active',
        ),
    ]
