# Generated by Django 4.1.6 on 2023-09-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_lug_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='وزن'),
        ),
    ]
