# Generated by Django 4.1.6 on 2023-09-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_image', models.ImageField(upload_to='images/about_us', verbose_name='عکس سر تیتر')),
                ('first_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='عنوان اول')),
                ('first_text', models.TextField(blank=True, null=True, verbose_name='متن اول')),
                ('second_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='عنوان دوم')),
                ('second_text', models.TextField(blank=True, null=True, verbose_name='متن دوم')),
                ('third_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='عنوان سوم')),
                ('third_text', models.TextField(blank=True, null=True, verbose_name='متن سوم')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/expert', verbose_name='عکس')),
                ('roll', models.CharField(max_length=30, verbose_name='نقش')),
                ('email', models.EmailField(blank=True, max_length=40, null=True, verbose_name='ایمیل')),
                ('face_book', models.CharField(blank=True, max_length=70, null=True, verbose_name='فیس بوک')),
                ('twitter', models.CharField(blank=True, max_length=70, null=True, verbose_name='تویتر')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
