# Generated by Django 4.1.6 on 2023-09-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'لیست درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'کارشناس', 'verbose_name_plural': 'کارشناسان'},
        ),
    ]
