# Generated by Django 4.1.6 on 2023-09-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_about_us_options_alter_expert_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='third_text',
        ),
        migrations.AddField(
            model_name='about_us',
            name='first_goal_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن طبقه بندی شده اول'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='second_goal_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن طبقه بندی شده سوم'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='third_goal_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن طبقه بندی شده سوم'),
        ),
    ]
