# Generated by Django 4.1.6 on 2023-09-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_remove_about_us_third_text_about_us_first_goal_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='second_text',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='third_title',
        ),
    ]
