# Generated by Django 4.1.6 on 2023-09-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_rename_about_us_aboutus_alter_expert_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
