# Generated by Django 4.1.6 on 2023-09-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='عکس اسلایدر')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('date', models.DateField(verbose_name='ناریخ ساخت')),
                ('link', models.CharField(max_length=60, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
