# Generated by Django 4.1 on 2023-08-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('text_massege', models.TextField(max_length=400, verbose_name='متن درخواست')),
            ],
        ),
    ]
