# Generated by Django 4.1.6 on 2023-09-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contactus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_title', models.CharField(max_length=20, verbose_name='عنوان سمت راست')),
                ('fist_right_text', models.CharField(max_length=30, verbose_name=' اولین متن سمت راست')),
                ('second_right_text', models.CharField(max_length=30, verbose_name='دومین متن سمت راست')),
                ('left_title', models.CharField(max_length=30, verbose_name='عنوان سمت چپ')),
                ('left_text', models.CharField(max_length=30, verbose_name='متن سمت چپ')),
                ('address', models.CharField(max_length=100, verbose_name='ادرس')),
                ('phone_no', models.CharField(max_length=100, verbose_name='تلفن')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('work_time', models.CharField(max_length=120, verbose_name='ساعت کاری')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس با ما',
                'verbose_name_plural': 'لیست اطلاعات تماس با ما',
            },
        ),
    ]
