# Generated by Django 4.1.6 on 2023-09-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_contactusinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': '  فرم تماس با ما', 'verbose_name_plural': 'فرم لیست تماس با ما'},
        ),
        migrations.AddField(
            model_name='contactusinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='fist_right_text',
            field=models.CharField(max_length=120, verbose_name=' اولین متن سمت راست'),
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='left_text',
            field=models.CharField(max_length=120, verbose_name='متن سمت چپ'),
        ),
        migrations.AlterField(
            model_name='contactusinfo',
            name='second_right_text',
            field=models.CharField(max_length=120, verbose_name='دومین متن سمت راست'),
        ),
    ]
